version: '3.8'
services:
  backend_mysql_db_ttrpg_tno:
    image: mysql:8
    # container_name: con_mysql_backend_tno
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_dane:/var/lib/mysql

volumes:
  mysql_dane:
